=== agabor/szamlazz-hu-sdk/SzamlazzHuTest/xmlszamla.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.szamlazz.hu/xmlszamla" xmlns:tns="http://www.szamlazz.hu/xmlszamla" elementFormDefault="qualified">

    <complexType name="vevoTipus">
        <sequence>
            <element name="nev" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="orszag" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="irsz" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="telepules" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="cim" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="email" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="sendEmail" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="adoalany" type="int" maxOccurs="1" minOccurs="0"></element>            <!-- Possible values for the "type" field: 7:business is based outside of the European Union, 6:business is based in the Europen Union, 1: has a hungarian tax number, 0: we don't know, if the buyer has a tax number, -1: no tax number -->
            <element name="adoszam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="adoszamEU" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="postazasiNev" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="postazasiOrszag" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="postazasiIrsz" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="postazasiTelepules" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="postazasiCim" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="vevoFokonyv" type="tns:vevoFokonyvTipus" maxOccurs="1" minOccurs="0"></element>                        
            <element name="azonosito" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="alairoNeve" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="telefonszam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="megjegyzes" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="vevoFokonyvTipus">
        <sequence>
            <element name="konyvelesDatum" type="date" maxOccurs="1" minOccurs="0"></element>
            <element name="vevoAzonosito" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="vevoFokonyviSzam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="folyamatosTelj" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="elszDatumTol" type="date" maxOccurs="1" minOccurs="0"></element>
            <element name="elszDatumIg" type="date" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="eladoTipus">
        <sequence>
            <element name="bank" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="bankszamlaszam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="emailReplyto" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="emailTargy" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="emailSzoveg" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="alairoNeve" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="beallitasokTipus">
        <sequence>
            <element name="felhasznalo" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="jelszo" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="szamlaagentkulcs" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="eszamla" type="boolean" maxOccurs="1" minOccurs="1"></element>
            <element name="kulcstartojelszo" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="szamlaLetoltes" type="boolean" maxOccurs="1" minOccurs="1"></element>
            <element name="szamlaLetoltesPld" type="int" maxOccurs="1" minOccurs="0"></element>
            <element name="valaszVerzio" type="int" maxOccurs="1" minOccurs="0"></element>
            <element name="aggregator" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="tetelTipus">
        <sequence>
            <element name="megnevezes" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="azonosito" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="mennyiseg" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="mennyisegiEgyseg" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="nettoEgysegar" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="afakulcs" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="arresAfaAlap" type="double" maxOccurs="1" minOccurs="0"></element>                        
            <element name="nettoErtek" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="afaErtek" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="bruttoErtek" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="megjegyzes" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="tetelFokonyv" type="tns:tetelFokonyvTipus" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="tetelekTipus">
        <sequence>
            <element name="tetel" type="tns:tetelTipus" maxOccurs="unbounded" minOccurs="1"></element>
        </sequence>
    </complexType>

    <complexType name="tetelFokonyvTipus">
        <sequence>
            <element name="gazdasagiEsem" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="gazdasagiEsemAfa" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="arbevetelFokonyviSzam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="afaFokonyviSzam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="elszDatumTol" type="date" maxOccurs="1" minOccurs="0"></element>
            <element name="elszDatumIg" type="date" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="fejlecTipus">
        <sequence>
            <element name="keltDatum" type="date" maxOccurs="1" minOccurs="1"></element>
            <element name="teljesitesDatum" type="date" maxOccurs="1" minOccurs="1"></element>
            <element name="fizetesiHataridoDatum" type="date" maxOccurs="1" minOccurs="1"></element>
            <element name="fizmod" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="penznem" type="string" maxOccurs="1"    minOccurs="1"></element>
            <element name="szamlaNyelve" type="tns:szamlaNyelveTipus" maxOccurs="1" minOccurs="1"></element>
            <element name="megjegyzes" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="arfolyamBank" type="string" maxOccurs="1" minOccurs="0"></element>   
            <element name="arfolyam" type="double" maxOccurs="1" minOccurs="0"></element>            <!-- If arfolyamBank='MNB' AND ther is no exchange rate, then the current exchange rate of MNB  will be used durring receipt creation (automatic MNB exchange rate import) -->
            <element name="rendelesSzam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="dijbekeroSzamlaszam" type="string" maxOccurs="1" minOccurs="0"></element> <!-- link to prepayment request -->
            <element name="elolegszamla" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="vegszamla" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="helyesbitoszamla" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="helyesbitettSzamlaszam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="dijbekero" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="szallitolevel" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="logoExtra" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="szamlaszamElotag" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="fizetendoKorrekcio" type="double" maxOccurs="1" minOccurs="0"></element>
            <element name="fizetve" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="arresAfa" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="szamlaSablon" type="string" maxOccurs="1" minOccurs="0"></element>       <!-- Codomain: 'SzlaMost' | 'SzlaAlap' | 'SzlaNoEnv' | 'Szla8cm' | 'SzlaTomb' | 'szlafuvarlevelesalap'-->
        </sequence>
    </complexType>

    <simpleType name="szamlaNyelveTipus">
        <restriction base="string">
            <enumeration value="hu"></enumeration>
            <enumeration value="en"></enumeration>
            <enumeration value="de"></enumeration>
            <enumeration value="it"></enumeration>
            <enumeration value="ro"></enumeration>
            <enumeration value="sk"></enumeration>
            <enumeration value="hr"></enumeration>
            <enumeration value="fr"></enumeration>
            <enumeration value="es"></enumeration>
            <enumeration value="cz"></enumeration>
            <enumeration value="pl"></enumeration>
        </restriction>
    </simpleType>

    <complexType name="transoflexTipus">
        <sequence>
            <!-- 5 digit number provided by TOF -->
            <element name="azonosito" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="shipmentID" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="csomagszam" type="int" maxOccurs="1" minOccurs="0"></element>
            <element name="countryCode" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="zip" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="service" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="sprinterTipus">
        <sequence>
            <!-- 3-character abbreviation agreed with Sprinter -->
            <element name="azonosito" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- 10-character long "felad칩k칩d" provided by Sprinter -->
            <element name="feladokod" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- "Ir치nyk칩d" from Sprinter is Sprinters own special parcel shipment code, eg. "106" -->
            <element name="iranykod" type="string" maxOccurs="1" minOccurs="0"></element>
            <!--    Number of packages, this shows how many consignment note will be attached to the receipt-->
            <element name="csomagszam" type="int" maxOccurs="1" minOccurs="0"></element>
            <!-- unique per receipt, 7-13 characters long identifyer -->
            <element name="vonalkodPostfix" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- usually this is the 1 work day note -->
            <element name="szallitasiIdo" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="pppTipus">
        <sequence>
            <!-- 3-character abbreviation agreed with PPP -->
            <element name="vonalkodPrefix" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- unique per receipt, MAX 7 characters long identifyer -->
            <element name="vonalkodPostfix" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="mplTipus">
        <sequence>
            <!-- MPL customer code -->
            <element name="vevokod" type="string" maxOccurs="1" minOccurs="1"></element>
            <!-- Bar code is generated based on thes string -->
            <element name="vonalkod" type="string" maxOccurs="1" minOccurs="1"></element>
            <!-- Weight of the package, can contain a decimal point, if necessary -->
            <element name="tomeg" type="string" maxOccurs="1" minOccurs="1"></element>
            <!-- Optional configuration for special services icons, if not defined no icon will be shown -->
            <element name="kulonszolgaltatasok" type="string" maxOccurs="1" minOccurs="0"></element>
            <!--    Vallue ("erteknyilvanitas") field on the consignment note -->
            <element name="erteknyilvanitas" type="double" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="fuvarlevelTipus">
        <sequence>
            <!-- TODO   the destination ("uticel") field is not used, should be removed after 2014.05.30, sprinter/iranykod field should be used instead  -->
            <element name="uticel" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- Codomain: TOF, PPP, SPRINTER, FOXPOST, EMPTY ,not necessary if there is no consignment note -->
            <element name="futarSzolgalat" type="string" maxOccurs="1" minOccurs="0"></element>
            <!--General bar code definition, this will be used, if no carrierspecific data is defined -->
            <element name="vonalkod" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- Comment on the consignment note -->
            <element name="megjegyzes" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- Trans-O-Flex node to upload -->
            <element name="tof" type="tns:transoflexTipus" maxOccurs="1" minOccurs="0"></element>
            <!-- PickPackPoint node to upload -->
            <element name="ppp" type="tns:pppTipus" maxOccurs="1" minOccurs="0"></element>
            <!-- Sprinter node to upload -->
            <element name="sprinter" type="tns:sprinterTipus" maxOccurs="1" minOccurs="0"></element>
            <!-- MPL node to upload-->
            <element name="mpl" type="tns:mplTipus" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <element name="xmlszamla">
        <complexType>
            <sequence>
                <element name="beallitasok" type="tns:beallitasokTipus" maxOccurs="1" minOccurs="1"></element>
                <element name="fejlec" type="tns:fejlecTipus" maxOccurs="1" minOccurs="1"></element>
                <element name="elado" type="tns:eladoTipus" maxOccurs="1" minOccurs="1"></element>
                <element name="vevo" type="tns:vevoTipus" maxOccurs="1" minOccurs="1"></element>
                <element name="fuvarlevel" type="tns:fuvarlevelTipus" maxOccurs="1" minOccurs="0"></element>
                <element name="tetelek" type="tns:tetelekTipus" maxOccurs="1" minOccurs="1"></element>
            </sequence>
        </complexType>
    </element>
</schema>

=== agabor/szamlazz-hu-sdk/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<xmlszamla xmlns="http://www.szamlazz.hu/xmlszamla" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.szamlazz.hu/xmlszamla https://www.szamlazz.hu/szamla/docs/xsds/agent/xmlszamla.xsd">
<!-- A számla alapbeállításai -->
    <beallitasok>
        <!-- Számla Agent kulcsot a számlázz.hu-ra belépve tudsz generálni -->
        <szamlaagentkulcs>Please fill!</szamlaagentkulcs>
        <eszamla>true</eszamla>
        <!-- „true” ha e-számlát kell létrehozni -->
        <szamlaLetoltes>true</szamlaLetoltes>
        <!-- „true” ha szeretnéd a választ PDF számlaként megkapni -->
        <valaszVerzio>1</valaszVerzio>
        <!-- 1: egyszerű szöveges vagy PDF válasz.
             2: XML válasz, ha a PDF-et is kéred, az XML-ben kerül elküldésre base64 kódolással -->
        <aggregator></aggregator>
        <!-- ez a tag kihagyható -->
        <szamlaKulsoAzon></szamlaKulsoAzon> <!--A számla ezzel a kulccsal azonosítható a harmadik fél rendszerében (a rendszer, amely használja a Számla Agentet): később ezzel a kulccsal le lehet kérdezni a számlát -->
    </beallitasok>
    <!-- fejléc adatok -->
    <fejlec>
        <teljesitesDatum>2025-01-20</teljesitesDatum>
        <!-- teljesítés dátuma -->
        <fizetesiHataridoDatum>2025-01-20</fizetesiHataridoDatum>
        <!-- fizetési határidő -->
        <fizmod>Átutalás</fizmod>
        <!-- fizetési mód: látható, ha a számlát böngészőből készíted -->
        <penznem>HUF</penznem>
        <!-- pénznem: látható, ha a számlát böngészőből készíted -->
        <szamlaNyelve>hu</szamlaNyelve>
        <!-- számla nyelve, lehet: de, en, it, hu, fr, ro, sk, hr -->
        <megjegyzes>Invoce comment</megjegyzes>
        <!-- számla megjegyzése -->
        <arfolyamBank>MNB</arfolyamBank>
        <!-- bank neve: ha a számla nem HUF-ban van, fel kell tüntetni, melyik bank árfolyamát használtuk az ÁFA kiszámításához -->
        <arfolyam>0.0</arfolyam>
        <!-- árfolyam: ha a számla nem HUF-ban van, fel kell tüntetni, melyik bank árfolyamát használtuk az ÁFA kiszámításához -->
        <rendelesSzam></rendelesSzam>
        <!-- rendelési szám -->
        <dijbekeroSzamlaszam></dijbekeroSzamlaszam>
        <!-- hivatkozás a díjbekérő számlaszámra -->
        <elolegszamla>false</elolegszamla>
        <!-- előlegszámla -->
        <vegszamla>false</vegszamla>
        <!-- végszámla (előlegszámla után) -->
        <helyesbitoszamla>false</helyesbitoszamla>
        <!-- helyesbítő számla -->
        <helyesbitettSzamlaszam></helyesbitettSzamlaszam>
        <!-- a helyesbített számla száma -->
        <dijbekero>false</dijbekero>
        <!-- díjbekérő számla -->
        <szamlaszamElotag></szamlaszamElotag>
        <!-- A számlázz.hu-ban használható Előtagok egyike - Beállítások / Előtagok -->
    </fejlec>
    <elado>
        <!-- A kereskedő adatai -->
        <bank>BB</bank>
        <!-- bank neve -->
        <bankszamlaszam>11111111-22222222-33333333</bankszamlaszam>
        <!-- bankszámlaszám -->
        <emailReplyto></emailReplyto>
        <!-- válaszcím (e-mail) -->
        <emailTargy>Invoice notification</emailTargy>
        <!-- e-mail tárgya -->
        <emailSzoveg>mail text</emailSzoveg>
        <!-- e-mail szövege -->
    </elado>
    <vevo>
        <!-- Vevő adatai -->
        <nev>Kovacs Bt.</nev>
        <!-- név -->
        <irsz>2030</irsz>
        <!-- irányítószám -->
        <telepules>Érd</telepules>
        <!-- város -->
        <cim>Tárnoki út 23.</cim>
        <!-- cím -->
        <email>buyer@example.com</email>
        <!-- e-mail cím, ha megadja, erre a címre elküldjük a számlát -->
        <sendEmail>false</sendEmail>
        <!-- küldjük-e el e-mailben az ügyfélnek (e-mail) -->
        <adoszam>12345678-1-42</adoszam>
        <!-- adószám/adóazonosító jel -->
        <postazasiNev>Kovács Bt. mailing name</postazasiNev>
        <!-- szállítási név/postai név -->
        <postazasiIrsz>2040</postazasiIrsz>
        <!-- szállítási irányítószám/postai irányítószám -->
        <postazasiTelepules>Budaörs</postazasiTelepules>
        <!-- szállítási város/postai város -->
        <postazasiCim>Szivárvány utca 8.</postazasiCim>
        <!-- szállítási cím/postai cím -->
        <azonosito>1234</azonosito>
        <!-- azonosító -->
        <telefonszam>Tel:+3630-555-55-55, Fax:+3623-555-555</telefonszam>
        <!-- telefonszám -->
        <megjegyzes>Call extension 214 from the reception</megjegyzes>
        <!-- megjegyzés -->
    </vevo>
    <fuvarlevel>
        <!-- fuvarlevél/szállítólevél. ha nem kell, hagyd üresen -->
        <uticel></uticel>
        <futarSzolgalat></futarSzolgalat>
    </fuvarlevel>
    <tetelek>
        <!-- számlán lévő tételek -->
        <tetel>
            <!-- 1. tétel -->
            <megnevezes>Elado izé</megnevezes>
            <!-- megnevezés -->
            <mennyiseg>1.0</mennyiseg>
            <!-- mennyiség -->
            <mennyisegiEgyseg>db</mennyisegiEgyseg>
            <!-- mennyiségi egység -->
            <nettoEgysegar>10000</nettoEgysegar>
            <!-- nettó egységár -->
            <afakulcs>27</afakulcs>
            <!-- ÁFA kulcs -->
            <nettoErtek>10000.0</nettoErtek>
            <!-- nettó érték -->
            <afaErtek>2700.0</afaErtek>
            <!-- ÁFA érték -->
            <bruttoErtek>12700.0</bruttoErtek>
            <!-- bruttó érték -->
            <megjegyzes>lorem ipsum</megjegyzes>
            <!-- tétel megjegyzése -->
        </tetel>
        <tetel>
            <!-- 2. tétel, részletek azonosak a fentiekkel -->
            <megnevezes>Elado izé 2</megnevezes>
            <mennyiseg>2.0</mennyiseg>
            <mennyisegiEgyseg>db</mennyisegiEgyseg>
            <nettoEgysegar>10000</nettoEgysegar>
            <afakulcs>27</afakulcs>
            <nettoErtek>20000.0</nettoErtek>
            <afaErtek>5400.0</afaErtek>
            <bruttoErtek>25400.0</bruttoErtek>
            <megjegyzes>lorem ipsum 2</megjegyzes>
        </tetel>
    </tetelek>
</xmlszamla>

=== agabor/szamlazz-hu-sdk/SzamlazzHuTest/testCreateInvoiceRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<xmlszamla xmlns="http://www.szamlazz.hu/xmlszamla" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.szamlazz.hu/xmlszamla https://www.szamlazz.hu/szamla/docs/xsds/agent/xmlszamla.xsd">
    <beallitasok>
        <!-- settings -->
        <felhasznalo>teszt01</felhasznalo>
        <!-- a Számlázz.hu user -->
        <jelszo>teszt01</jelszo>
        <!-- a Számlázz.hu’s user password -->
        <szamlaagentkulcs>Please fill!</szamlaagentkulcs>
        <eszamla>true</eszamla>
        <!-- „true” in case you need to create an e-invoice -->
        <szamlaLetoltes>true</szamlaLetoltes>
        <!-- „true” in case you would like to get the 
                                             PDF invoice in the response -->
        <valaszVerzio>2</valaszVerzio>
        <!-- 1: gives a simple text or PDF as answer. 
                                             2: xml answer, in case you asked for the PDF as well,
                                                it will be included in the XML with base64 coding.
                                         -->
        <aggregator></aggregator>
        <!-- omit this tag -->
    </beallitasok>
    <fejlec>
        <!-- header -->
        <keltDatum>2020-01-20</keltDatum>
        <!-- creating date, in this exact format -->
        <teljesitesDatum>2020-01-20</teljesitesDatum>
        <!-- payment date -->
        <fizetesiHataridoDatum>2020-01-20</fizetesiHataridoDatum>
        <!-- due date -->
        <fizmod>átutalás</fizmod>
        <!-- payment type: it can be seen in case you create the invoice 
                                 from browser -->
        <penznem>HUF</penznem>
        <!-- currency: it can be seen in case you create the invoice 
                                 from browser -->
        <szamlaNyelve>hu</szamlaNyelve>
        <!-- language of invoice, can  be: de, en, it, hu, fr, ro, sk, hr
                                   -->
        <megjegyzes>Invoce comment</megjegyzes>
        <!-- comment of the invoice -->
        <arfolyamBank>MNB</arfolyamBank>
        <!-- name of bank: in case of invoice about other currency 
                                          than HUF you have to display which bank’s exchange rates 
                                          did we use to calculate VAT -->
        <arfolyam>0.00</arfolyam>
        <!-- exchange rate: in case of invoice about other currency 
                                          than HUF you have to display which bank’s exchange rates 
                                          did we use to calculate VAT -->
        <rendelesSzam></rendelesSzam>
        <!-- order number -->
        <dijbekeroSzamlaszam></dijbekeroSzamlaszam>
        <!-- reference to pro forma invoice number -->
        <elolegszamla>false</elolegszamla>
        <!-- deposit invoice -->
        <vegszamla>false</vegszamla>
        <!-- invoice (after a deposit invoice) -->
        <helyesbitoszamla>false</helyesbitoszamla>
        <!-- correction invoice -->
        <helyesbitettSzamlaszam></helyesbitettSzamlaszam>
        <!-- the number of the corrected invoice -->
        <dijbekero>false</dijbekero>
        <!-- proform invoice -->
        <szamlaszamElotag></szamlaszamElotag>
        <!-- One of the prefixes from the invoice pad menu  -->
        <fizetve>false</fizetve>
		<szamlaSablon>Szla8cm</szamlaSablon>
    </fejlec>
    <elado>
        <!-- Details of the merchant-->
        <bank>BB</bank>
        <!-- bank name -->
        <bankszamlaszam>11111111-22222222-33333333</bankszamlaszam>
        <!-- bank account -->
        <emailReplyto></emailReplyto>
        <!-- reply e-mail address -->
        <emailTargy>Invoice notification</emailTargy>
        <!-- e-mail subject -->
        <emailSzoveg>mail text</emailSzoveg>
        <!-- text of e-mail -->
    </elado>
    <vevo>
        <!--Buyer details -->
        <nev>Kovács &amp; Társa Bt.</nev>
        <!-- name -->
        <orszag>Magyarország</orszag>
        <!-- Country -->
        <irsz>2030</irsz>
        <!-- ZIP code -->
        <telepules>Érd</telepules>
        <!-- city -->
        <cim>Tárnoki út 23.</cim>
        <!-- address -->
        <email>buyer@example.com</email>
        <!-- e-mail address, if given, we will send the invoice to this mail address -->
        <sendEmail>false</sendEmail>
        <!-- should we send the e-mail to the customer (by email) -->
        <adoszam>12345678-1-42</adoszam>
        <!-- fiscal number/tax number -->
        <adoszamEU>HU12345678</adoszamEU>
        <!-- eu tax number -->
        <postazasiNev>Kovács Bt. mailing name</postazasiNev>
        <!--delivery name/postal name -->
        <postazasiIrsz>2040</postazasiIrsz>
        <!--delivery ZIP code/postal ZIP code -->
        <postazasiTelepules>Budaörs</postazasiTelepules>
        <!--delivery city/postal city -->
        <postazasiCim>Szivárvány utca 8.</postazasiCim>
        <!--delivery address/postal address -->
        <azonosito>1234</azonosito>
        <!-- identification -->
        <telefonszam>Tel:+3630-555-55-55, Fax:+3623-555-555</telefonszam>
        <!-- phone number -->
        <megjegyzes>Call extension 214 from the reception</megjegyzes>
        <!-- comment -->
    </vevo>
    <fuvarlevel>
        <!-- waybill/confinement note, you do not need this: omit the entire tag -->
        <uticel></uticel>
        <futarSzolgalat></futarSzolgalat>
    </fuvarlevel>
    <tetelek>
        <!-- items on invoice -->
        <tetel>
            <!-- item 1 -->
            <megnevezes>Elado izé</megnevezes>
            <!-- name -->
            <mennyiseg>1.00</mennyiseg>
            <!-- quantity -->
            <mennyisegiEgyseg>db</mennyisegiEgyseg>
            <!-- unit of quantity -->
            <nettoEgysegar>10000.00</nettoEgysegar>
            <!-- unit price -->
            <afakulcs>27.0</afakulcs>
            <!-- VAT rate -->
            <nettoErtek>10000.00</nettoErtek>
            <!-- net price -->
            <afaErtek>2700.00</afaErtek>
            <!-- VAT amount -->
            <bruttoErtek>12700.00</bruttoErtek>
            <!-- gross amount -->
            <megjegyzes>lorem ipsum</megjegyzes>
            <!-- comment for item -->
        </tetel>
        <tetel>
            <!-- item 2, details are same as above -->
            <megnevezes>Elado izé 2</megnevezes>
            <mennyiseg>2.00</mennyiseg>
            <mennyisegiEgyseg>db</mennyisegiEgyseg>
            <nettoEgysegar>10000.00</nettoEgysegar>
            <afakulcs>27.0</afakulcs>
            <nettoErtek>20000.00</nettoErtek>
            <afaErtek>5400.00</afaErtek>
            <bruttoErtek>25400.00</bruttoErtek>
            <megjegyzes>lorem ipsum 2</megjegyzes>
        </tetel>
    </tetelek>
</xmlszamla>
